# Remove Gold Drops from Mobs liks Piglins? (default: true)
removeGoldDrop: true
# Should the plugin check for updated? (default: true)
updateCheck: true
# Valid language are: de_DE, en_EN
language: "en_EN"
# Do you want to restrict bank commands to bank plots (requires Towny)
restrictToBankPlot: false
