# Infos
name: GoldEconomy
version: '1.0'
description: A simple gold based Economy plugin that just works.
author: ConfusedAlex
api-version: 1.18

# Data
load: STARTUP
main: confusedalex.goldeconomy.GoldEconomy
loadbefore: [Towny]
depend: [Vault]