# Infos
name: TheGoldEconomy
version: '1.2'
description: A simple gold based Economy plugin that just works.
author: ConfusedAlex
api-version: 1.19

# Data
load: STARTUP
main: confusedalex.thegoldeconomy.TheGoldEconomy
loadbefore: [Towny]
depend: [Vault]